compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 2
mixed_precision: bf16
machine_rank: 0
num_machines: 1
rdzv_backend: static
same_network: true
main_training_function: main
use_cpu: false
deepspeed_config:
  zero_stage: 2
  offload_optimizer_device: none
  offload_param_device: none
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  zero3_init_flag: false
gradient_checkpointing: true
