"""Persistence and LLM-glue for the Ask-Claude follow-up chat on a suggestion.

Each user-typed message and each assistant reply is stored in
``suggestion_chat_messages`` so the conversation survives page reloads. The
assistant turn is generated by ``llm_chat.chat_completion`` with the original
suggestion injected as system context — the LLM gets the rationale, evidence,
and tradeoffs, then answers operator questions like "why this learning rate?"
without re-running the recommendation pipeline.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ProjectNotFoundError, SuggestionNotFoundError
from app.models.project import Project
from app.models.suggestion import AISuggestion
from app.models.suggestion_chat_message import SuggestionChatMessage
from app.schemas.suggestion_chat import (
    SuggestionChatListResponse,
    SuggestionChatMessageResponse,
)
from app.services import llm_chat
from app.services.settings_service import get_raw_api_key, get_settings

_SYSTEM_PROMPT_TEMPLATE = """You are an expert ML training advisor. The operator has received the
following suggestion from the workbench's rule engine or recommendation model
and may ask follow-up questions about it. Stay grounded in the suggestion's
rationale and evidence — do not invent new config diffs. If the operator asks
about an alternative, explain the tradeoff in plain language.

## Suggestion rationale
{rationale}

## Expected effect
{expected_effect}

## Tradeoffs
{tradeoffs}

## Proposed config changes (JSON)
{config_diff}

## Evidence (JSON)
{evidence}
"""


async def _get_project(*, session: AsyncSession, project_id: str) -> Project:
    result = await session.execute(select(Project).where(Project.id == project_id))
    project = result.scalar_one_or_none()
    if project is None:
        raise ProjectNotFoundError(project_id)
    return project


async def _get_suggestion(
    *, session: AsyncSession, project_id: str, suggestion_id: str
) -> AISuggestion:
    result = await session.execute(
        select(AISuggestion).where(
            AISuggestion.id == suggestion_id, AISuggestion.project_id == project_id
        )
    )
    suggestion = result.scalar_one_or_none()
    if suggestion is None:
        raise SuggestionNotFoundError(suggestion_id)
    return suggestion


async def list_messages(
    *, session: AsyncSession, project_id: str, suggestion_id: str
) -> SuggestionChatListResponse:
    await _get_project(session=session, project_id=project_id)
    await _get_suggestion(
        session=session, project_id=project_id, suggestion_id=suggestion_id
    )
    result = await session.execute(
        select(SuggestionChatMessage)
        .where(SuggestionChatMessage.suggestion_id == suggestion_id)
        .order_by(SuggestionChatMessage.created_at)
    )
    rows = list(result.scalars().all())
    return SuggestionChatListResponse(
        messages=[SuggestionChatMessageResponse.model_validate(row) for row in rows]
    )


def _build_system_prompt(*, suggestion: AISuggestion) -> str:
    return _SYSTEM_PROMPT_TEMPLATE.format(
        rationale=suggestion.rationale,
        expected_effect=suggestion.expected_effect or "—",
        tradeoffs=suggestion.tradeoffs or "—",
        config_diff=suggestion.config_diff,
        evidence=suggestion.evidence_json or "[]",
    )


async def send_message(
    *,
    session: AsyncSession,
    project_id: str,
    suggestion_id: str,
    message: str,
) -> SuggestionChatMessageResponse:
    await _get_project(session=session, project_id=project_id)
    suggestion = await _get_suggestion(
        session=session, project_id=project_id, suggestion_id=suggestion_id
    )

    now = datetime.now(UTC).isoformat()
    user_row = SuggestionChatMessage(
        id=str(uuid.uuid4()),
        suggestion_id=suggestion_id,
        role="user",
        content=message,
        created_at=now,
    )
    session.add(user_row)
    await session.flush()

    history_result = await session.execute(
        select(SuggestionChatMessage)
        .where(SuggestionChatMessage.suggestion_id == suggestion_id)
        .order_by(SuggestionChatMessage.created_at)
    )
    history_rows = list(history_result.scalars().all())

    current_settings = get_settings()
    assistant_text = await llm_chat.chat_completion(
        provider=current_settings.ai_provider,
        api_key=get_raw_api_key(),
        model_id=current_settings.ai_model_id,
        base_url=current_settings.ai_base_url,
        system=_build_system_prompt(suggestion=suggestion),
        messages=[
            {"role": row.role, "content": row.content} for row in history_rows
        ],
    )

    assistant_row = SuggestionChatMessage(
        id=str(uuid.uuid4()),
        suggestion_id=suggestion_id,
        role="assistant",
        content=assistant_text,
        created_at=datetime.now(UTC).isoformat(),
    )
    session.add(assistant_row)
    await session.commit()
    await session.refresh(assistant_row)
    return SuggestionChatMessageResponse.model_validate(assistant_row)
